#!/bin/sh
# clear all cells

jupyter-nbconvert --ClearOutputPreprocessor.enabled=True --inplace **.ipynb
jupyter-nbconvert --ClearOutputPreprocessor.enabled=True --inplace **/**.ipynb
jupyter-nbconvert --ClearOutputPreprocessor.enabled=True --inplace **/**/**.ipynb
